Lesson6 hw
DenisSvekla/Lesson6 pull request #3
Opened 2021-12-07 20:37 UTC by DenisSvekla

2021-12-13 11:38 UTC, wildpioneer requested changes

2021-12-13 11:38 UTC, wildpioneer commented on src/test/java/tests/HW.java
> +        System.setProperty("webdriver.chrome.driver", "src/test/resources/chromedriver.exe");
Старайся разделять вводами логические блоки кода, чтобы он стал более читаемым.

2021-12-13 11:38 UTC, wildpioneer commented on src/test/java/tests/HW.java
> +        String expectedlayingArea = "31.76 м2.";
Блок инициализации данных лучше выносить сразу после начала метода

2021-12-13 11:38 UTC, wildpioneer commented on src/test/java/tests/HW.java
> +        driver.manage().deleteAllCookies();
Необходимо группировать логические блоки, например:
1) Настройка данных
2) Настройка браузера
3) и т.д.

2021-12-13 11:38 UTC, wildpioneer commented on src/test/java/tests/HW.java
> +        leightInput.sendKeys("8,000");
Эти данные тоже можно вынести в переменные

2021-12-13 11:38 UTC, wildpioneer commented on src/test/java/tests/HW.java
> +
Не оставляй пустых строк в конце метода - это навивает на мысль, что тут что-то не законченно

2021-12-13 11:38 UTC, wildpioneer commented on src/test/java/tests/HW.java
> +        jse.executeScript("window.scrollBy(0,250)");
Почему именно скролирование по координатам?

2021-12-13 11:38 UTC, wildpioneer commented on src/test/java/tests/HW.java
> +
Закрытие драйвера в этом методе?

2021-12-13 20:31 UTC, DenisSvekla commented on src/test/java/tests/HW.java
> +        System.setProperty("webdriver.chrome.driver", "src/test/resources/chromedriver.exe");
Принял, в процессе

2021-12-13 20:31 UTC, DenisSvekla commented on src/test/java/tests/HW.java
> +        String expectedlayingArea = "31.76 м2.";
сейчас перенесем, запомнил

2021-12-13 20:32 UTC, DenisSvekla commented on src/test/java/tests/HW.java
> +        driver.manage().deleteAllCookies();
в процессе изменения

2021-12-13 20:32 UTC, DenisSvekla commented on src/test/java/tests/HW.java
> +
исправлено, в следующем пуше ветки такого не будет

2021-12-13 20:34 UTC, DenisSvekla commented on src/test/java/tests/HW.java
> +        jse.executeScript("window.scrollBy(0,250)");
Поскольку немного загораживалась кнопка и по координатам по мне лучший вариант, вероятнее всего можно также все сделать через try/catch в случае если увидит кнопку (поменяется расположение, браузер будет открыт не в полном окне) чтобы скрол не применялся

2021-12-13 20:35 UTC, DenisSvekla commented on src/test/java/tests/HW.java
> +
Моя ошибка, удалил для просмотра результатов на клиенте и в последующем из за неопытности, не добавил обратно.

2021-12-19 19:57 UTC, wildpioneer commented
Исправлено и проверено

2021-12-19 19:57 UTC, closed without merging