Test ng hw
DenisSvekla/Lesson6 pull request #8
Opened 2022-01-09 20:31 UTC by DenisSvekla

2022-01-17 10:51 UTC, wildpioneer requested changes

2022-01-17 10:51 UTC, wildpioneer commented on src/test/java/BaseTest.java
> +    //@BeforeTest
Удаляй все лишнее перед PR

2022-01-17 10:51 UTC, wildpioneer commented on src/test/java/HwDvisionTest.java
> +        Assert.assertEquals(ss,1,"Деление работает некорректно");
В комментарии надо добавлять текст, который дает четкое понимание, что именно сломалось

2022-01-17 10:51 UTC, wildpioneer commented on src/test/java/HwDvisionTest.java
> +    @Test (priority = 2,invocationCount = 6, threadPoolSize = 2)
Форматирование

2022-01-23 20:49 UTC, DenisSvekla commented on src/test/java/BaseTest.java
> +    //@BeforeTest
Согласен, удалил

2022-01-23 20:52 UTC, DenisSvekla commented on src/test/java/HwDvisionTest.java
> +        Assert.assertEquals(ss,1,"Деление работает некорректно");
Исправлено

2022-01-23 20:59 UTC, DenisSvekla commented on src/test/java/HwDvisionTest.java
> +    @Test (priority = 2,invocationCount = 6, threadPoolSize = 2)
Исправлено

2022-01-31 11:34 UTC, closed without merging